// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: poker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PokerService_EvaluateHand_FullMethodName            = "/poker.PokerService/EvaluateHand"
	PokerService_CompareHands_FullMethodName            = "/poker.PokerService/CompareHands"
	PokerService_CalculateWinProbability_FullMethodName = "/poker.PokerService/CalculateWinProbability"
)

// PokerServiceClient is the client API for PokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PokerServiceClient interface {
	EvaluateHand(ctx context.Context, in *EvaluateHandRequest, opts ...grpc.CallOption) (*EvaluateHandResponse, error)
	CompareHands(ctx context.Context, in *CompareHandsRequest, opts ...grpc.CallOption) (*CompareHandsResponse, error)
	CalculateWinProbability(ctx context.Context, in *WinProbabilityRequest, opts ...grpc.CallOption) (*WinProbabilityResponse, error)
}

type pokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPokerServiceClient(cc grpc.ClientConnInterface) PokerServiceClient {
	return &pokerServiceClient{cc}
}

func (c *pokerServiceClient) EvaluateHand(ctx context.Context, in *EvaluateHandRequest, opts ...grpc.CallOption) (*EvaluateHandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateHandResponse)
	err := c.cc.Invoke(ctx, PokerService_EvaluateHand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerServiceClient) CompareHands(ctx context.Context, in *CompareHandsRequest, opts ...grpc.CallOption) (*CompareHandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareHandsResponse)
	err := c.cc.Invoke(ctx, PokerService_CompareHands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokerServiceClient) CalculateWinProbability(ctx context.Context, in *WinProbabilityRequest, opts ...grpc.CallOption) (*WinProbabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WinProbabilityResponse)
	err := c.cc.Invoke(ctx, PokerService_CalculateWinProbability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokerServiceServer is the server API for PokerService service.
// All implementations must embed UnimplementedPokerServiceServer
// for forward compatibility.
type PokerServiceServer interface {
	EvaluateHand(context.Context, *EvaluateHandRequest) (*EvaluateHandResponse, error)
	CompareHands(context.Context, *CompareHandsRequest) (*CompareHandsResponse, error)
	CalculateWinProbability(context.Context, *WinProbabilityRequest) (*WinProbabilityResponse, error)
	mustEmbedUnimplementedPokerServiceServer()
}

// UnimplementedPokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPokerServiceServer struct{}

func (UnimplementedPokerServiceServer) EvaluateHand(context.Context, *EvaluateHandRequest) (*EvaluateHandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateHand not implemented")
}
func (UnimplementedPokerServiceServer) CompareHands(context.Context, *CompareHandsRequest) (*CompareHandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareHands not implemented")
}
func (UnimplementedPokerServiceServer) CalculateWinProbability(context.Context, *WinProbabilityRequest) (*WinProbabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateWinProbability not implemented")
}
func (UnimplementedPokerServiceServer) mustEmbedUnimplementedPokerServiceServer() {}
func (UnimplementedPokerServiceServer) testEmbeddedByValue()                      {}

// UnsafePokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PokerServiceServer will
// result in compilation errors.
type UnsafePokerServiceServer interface {
	mustEmbedUnimplementedPokerServiceServer()
}

func RegisterPokerServiceServer(s grpc.ServiceRegistrar, srv PokerServiceServer) {
	// If the following call panics, it indicates UnimplementedPokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PokerService_ServiceDesc, srv)
}

func _PokerService_EvaluateHand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateHandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServiceServer).EvaluateHand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerService_EvaluateHand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServiceServer).EvaluateHand(ctx, req.(*EvaluateHandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerService_CompareHands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareHandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServiceServer).CompareHands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerService_CompareHands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServiceServer).CompareHands(ctx, req.(*CompareHandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokerService_CalculateWinProbability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WinProbabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokerServiceServer).CalculateWinProbability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokerService_CalculateWinProbability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokerServiceServer).CalculateWinProbability(ctx, req.(*WinProbabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PokerService_ServiceDesc is the grpc.ServiceDesc for PokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poker.PokerService",
	HandlerType: (*PokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateHand",
			Handler:    _PokerService_EvaluateHand_Handler,
		},
		{
			MethodName: "CompareHands",
			Handler:    _PokerService_CompareHands_Handler,
		},
		{
			MethodName: "CalculateWinProbability",
			Handler:    _PokerService_CalculateWinProbability_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poker.proto",
}
