// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: poker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateHandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []string               `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"` // Exactly 7 cards
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateHandRequest) Reset() {
	*x = EvaluateHandRequest{}
	mi := &file_poker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateHandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateHandRequest) ProtoMessage() {}

func (x *EvaluateHandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateHandRequest.ProtoReflect.Descriptor instead.
func (*EvaluateHandRequest) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateHandRequest) GetCards() []string {
	if x != nil {
		return x.Cards
	}
	return nil
}

type EvaluateHandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandRank      string                 `protobuf:"bytes,1,opt,name=hand_rank,json=handRank,proto3" json:"hand_rank,omitempty"`     // e.g. "Royal Flush", "Two Pair"
	BestFive      []string               `protobuf:"bytes,2,rep,name=best_five,json=bestFive,proto3" json:"best_five,omitempty"`     // The 5 cards forming the best hand
	RankValue     int32                  `protobuf:"varint,3,opt,name=rank_value,json=rankValue,proto3" json:"rank_value,omitempty"` // Numeric rank for comparison (higher = better)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateHandResponse) Reset() {
	*x = EvaluateHandResponse{}
	mi := &file_poker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateHandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateHandResponse) ProtoMessage() {}

func (x *EvaluateHandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateHandResponse.ProtoReflect.Descriptor instead.
func (*EvaluateHandResponse) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateHandResponse) GetHandRank() string {
	if x != nil {
		return x.HandRank
	}
	return ""
}

func (x *EvaluateHandResponse) GetBestFive() []string {
	if x != nil {
		return x.BestFive
	}
	return nil
}

func (x *EvaluateHandResponse) GetRankValue() int32 {
	if x != nil {
		return x.RankValue
	}
	return 0
}

type CompareHandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player1Cards  []string               `protobuf:"bytes,1,rep,name=player1_cards,json=player1Cards,proto3" json:"player1_cards,omitempty"` // 7 cards for player 1
	Player2Cards  []string               `protobuf:"bytes,2,rep,name=player2_cards,json=player2Cards,proto3" json:"player2_cards,omitempty"` // 7 cards for player 2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareHandsRequest) Reset() {
	*x = CompareHandsRequest{}
	mi := &file_poker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareHandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareHandsRequest) ProtoMessage() {}

func (x *CompareHandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareHandsRequest.ProtoReflect.Descriptor instead.
func (*CompareHandsRequest) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{2}
}

func (x *CompareHandsRequest) GetPlayer1Cards() []string {
	if x != nil {
		return x.Player1Cards
	}
	return nil
}

func (x *CompareHandsRequest) GetPlayer2Cards() []string {
	if x != nil {
		return x.Player2Cards
	}
	return nil
}

type CompareHandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Winner        int32                  `protobuf:"varint,1,opt,name=winner,proto3" json:"winner,omitempty"` // 1, 2, or 0 for tie
	Player1Hand   *EvaluateHandResponse  `protobuf:"bytes,2,opt,name=player1_hand,json=player1Hand,proto3" json:"player1_hand,omitempty"`
	Player2Hand   *EvaluateHandResponse  `protobuf:"bytes,3,opt,name=player2_hand,json=player2Hand,proto3" json:"player2_hand,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"` // Human-readable result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareHandsResponse) Reset() {
	*x = CompareHandsResponse{}
	mi := &file_poker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareHandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareHandsResponse) ProtoMessage() {}

func (x *CompareHandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareHandsResponse.ProtoReflect.Descriptor instead.
func (*CompareHandsResponse) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{3}
}

func (x *CompareHandsResponse) GetWinner() int32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *CompareHandsResponse) GetPlayer1Hand() *EvaluateHandResponse {
	if x != nil {
		return x.Player1Hand
	}
	return nil
}

func (x *CompareHandsResponse) GetPlayer2Hand() *EvaluateHandResponse {
	if x != nil {
		return x.Player2Hand
	}
	return nil
}

func (x *CompareHandsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type WinProbabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoleCards     []string               `protobuf:"bytes,1,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`           // 2 hole cards for the player
	Community     []string               `protobuf:"bytes,2,rep,name=community,proto3" json:"community,omitempty"`                            // 0-5 community cards
	NumOpponents  int32                  `protobuf:"varint,3,opt,name=num_opponents,json=numOpponents,proto3" json:"num_opponents,omitempty"` // Number of opponents
	Iterations    int32                  `protobuf:"varint,4,opt,name=iterations,proto3" json:"iterations,omitempty"`                         // Number of Monte Carlo simulations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WinProbabilityRequest) Reset() {
	*x = WinProbabilityRequest{}
	mi := &file_poker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinProbabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinProbabilityRequest) ProtoMessage() {}

func (x *WinProbabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinProbabilityRequest.ProtoReflect.Descriptor instead.
func (*WinProbabilityRequest) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{4}
}

func (x *WinProbabilityRequest) GetHoleCards() []string {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

func (x *WinProbabilityRequest) GetCommunity() []string {
	if x != nil {
		return x.Community
	}
	return nil
}

func (x *WinProbabilityRequest) GetNumOpponents() int32 {
	if x != nil {
		return x.NumOpponents
	}
	return 0
}

func (x *WinProbabilityRequest) GetIterations() int32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

type WinProbabilityResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WinProbability  float64                `protobuf:"fixed64,1,opt,name=win_probability,json=winProbability,proto3" json:"win_probability,omitempty"`    // Winning percentage (0.0-100.0)
	TieProbability  float64                `protobuf:"fixed64,2,opt,name=tie_probability,json=tieProbability,proto3" json:"tie_probability,omitempty"`    // Tie percentage
	LossProbability float64                `protobuf:"fixed64,3,opt,name=loss_probability,json=lossProbability,proto3" json:"loss_probability,omitempty"` // Loss percentage
	IterationsRun   int32                  `protobuf:"varint,4,opt,name=iterations_run,json=iterationsRun,proto3" json:"iterations_run,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WinProbabilityResponse) Reset() {
	*x = WinProbabilityResponse{}
	mi := &file_poker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinProbabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinProbabilityResponse) ProtoMessage() {}

func (x *WinProbabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinProbabilityResponse.ProtoReflect.Descriptor instead.
func (*WinProbabilityResponse) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{5}
}

func (x *WinProbabilityResponse) GetWinProbability() float64 {
	if x != nil {
		return x.WinProbability
	}
	return 0
}

func (x *WinProbabilityResponse) GetTieProbability() float64 {
	if x != nil {
		return x.TieProbability
	}
	return 0
}

func (x *WinProbabilityResponse) GetLossProbability() float64 {
	if x != nil {
		return x.LossProbability
	}
	return 0
}

func (x *WinProbabilityResponse) GetIterationsRun() int32 {
	if x != nil {
		return x.IterationsRun
	}
	return 0
}

var File_poker_proto protoreflect.FileDescriptor

const file_poker_proto_rawDesc = "" +
	"\n" +
	"\vpoker.proto\x12\x05poker\"+\n" +
	"\x13EvaluateHandRequest\x12\x14\n" +
	"\x05cards\x18\x01 \x03(\tR\x05cards\"o\n" +
	"\x14EvaluateHandResponse\x12\x1b\n" +
	"\thand_rank\x18\x01 \x01(\tR\bhandRank\x12\x1b\n" +
	"\tbest_five\x18\x02 \x03(\tR\bbestFive\x12\x1d\n" +
	"\n" +
	"rank_value\x18\x03 \x01(\x05R\trankValue\"_\n" +
	"\x13CompareHandsRequest\x12#\n" +
	"\rplayer1_cards\x18\x01 \x03(\tR\fplayer1Cards\x12#\n" +
	"\rplayer2_cards\x18\x02 \x03(\tR\fplayer2Cards\"\xd0\x01\n" +
	"\x14CompareHandsResponse\x12\x16\n" +
	"\x06winner\x18\x01 \x01(\x05R\x06winner\x12>\n" +
	"\fplayer1_hand\x18\x02 \x01(\v2\x1b.poker.EvaluateHandResponseR\vplayer1Hand\x12>\n" +
	"\fplayer2_hand\x18\x03 \x01(\v2\x1b.poker.EvaluateHandResponseR\vplayer2Hand\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x99\x01\n" +
	"\x15WinProbabilityRequest\x12\x1d\n" +
	"\n" +
	"hole_cards\x18\x01 \x03(\tR\tholeCards\x12\x1c\n" +
	"\tcommunity\x18\x02 \x03(\tR\tcommunity\x12#\n" +
	"\rnum_opponents\x18\x03 \x01(\x05R\fnumOpponents\x12\x1e\n" +
	"\n" +
	"iterations\x18\x04 \x01(\x05R\n" +
	"iterations\"\xbc\x01\n" +
	"\x16WinProbabilityResponse\x12'\n" +
	"\x0fwin_probability\x18\x01 \x01(\x01R\x0ewinProbability\x12'\n" +
	"\x0ftie_probability\x18\x02 \x01(\x01R\x0etieProbability\x12)\n" +
	"\x10loss_probability\x18\x03 \x01(\x01R\x0flossProbability\x12%\n" +
	"\x0eiterations_run\x18\x04 \x01(\x05R\riterationsRun2\xf8\x01\n" +
	"\fPokerService\x12G\n" +
	"\fEvaluateHand\x12\x1a.poker.EvaluateHandRequest\x1a\x1b.poker.EvaluateHandResponse\x12G\n" +
	"\fCompareHands\x12\x1a.poker.CompareHandsRequest\x1a\x1b.poker.CompareHandsResponse\x12V\n" +
	"\x17CalculateWinProbability\x12\x1c.poker.WinProbabilityRequest\x1a\x1d.poker.WinProbabilityResponseB&Z$github.com/texasholdem/backend/protob\x06proto3"

var (
	file_poker_proto_rawDescOnce sync.Once
	file_poker_proto_rawDescData []byte
)

func file_poker_proto_rawDescGZIP() []byte {
	file_poker_proto_rawDescOnce.Do(func() {
		file_poker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poker_proto_rawDesc), len(file_poker_proto_rawDesc)))
	})
	return file_poker_proto_rawDescData
}

var file_poker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_poker_proto_goTypes = []any{
	(*EvaluateHandRequest)(nil),    // 0: poker.EvaluateHandRequest
	(*EvaluateHandResponse)(nil),   // 1: poker.EvaluateHandResponse
	(*CompareHandsRequest)(nil),    // 2: poker.CompareHandsRequest
	(*CompareHandsResponse)(nil),   // 3: poker.CompareHandsResponse
	(*WinProbabilityRequest)(nil),  // 4: poker.WinProbabilityRequest
	(*WinProbabilityResponse)(nil), // 5: poker.WinProbabilityResponse
}
var file_poker_proto_depIdxs = []int32{
	1, // 0: poker.CompareHandsResponse.player1_hand:type_name -> poker.EvaluateHandResponse
	1, // 1: poker.CompareHandsResponse.player2_hand:type_name -> poker.EvaluateHandResponse
	0, // 2: poker.PokerService.EvaluateHand:input_type -> poker.EvaluateHandRequest
	2, // 3: poker.PokerService.CompareHands:input_type -> poker.CompareHandsRequest
	4, // 4: poker.PokerService.CalculateWinProbability:input_type -> poker.WinProbabilityRequest
	1, // 5: poker.PokerService.EvaluateHand:output_type -> poker.EvaluateHandResponse
	3, // 6: poker.PokerService.CompareHands:output_type -> poker.CompareHandsResponse
	5, // 7: poker.PokerService.CalculateWinProbability:output_type -> poker.WinProbabilityResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_poker_proto_init() }
func file_poker_proto_init() {
	if File_poker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poker_proto_rawDesc), len(file_poker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poker_proto_goTypes,
		DependencyIndexes: file_poker_proto_depIdxs,
		MessageInfos:      file_poker_proto_msgTypes,
	}.Build()
	File_poker_proto = out.File
	file_poker_proto_goTypes = nil
	file_poker_proto_depIdxs = nil
}
